analytics: {}
color:
  brandColors:
    - '#000000'
    - '#6F1A16'
    - '#808090'
    - '#D84038'
    - '#80D090'
  brandStrength: 0.329954
  lightness: 0.688063
  rhythmicContrast: 0.120495
  saturation: 0.835585
cta: {}
layout_spectrum: 0.333333
name: Austin Found
opengraph: {}
purpose: []
typography_spectrum: 0.31259
