analytics: {}
color:
  brandColors:
    - '#ff751a'
    - '#640700'
    - '#eab92e'
    - '#8286b3'
    - '#fdfdfb'
  brandStrength: 0
  lightness: 0.515765
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 0.894144
name: Austin Found
opengraph: {}
purpose: []
typography_spectrum: 0.31259
