name: Austin Found
favicon: null
layout_spectrum: 0.51038
typography_spectrum: 0.38001
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dd0126'
    - '#00949c'
    - '#240203'
    - '#ff9998'
  brandStrength: 0.1875
  lightness: 0.688063
  saturation: 0.835585
  rhythmicContrast: 0.5
purpose: []
