analytics: {}
color:
  brandColors:
    - '#B0C0C0'
    - '#204858'
    - '#708888'
    - '#306078'
    - '#000000'
  brandStrength: 0
  lightness: 0.507882
  rhythmicContrast: 0.322072
  saturation: 0.5259
cta: {}
layout_spectrum: 0.333333
name: Austin Found
opengraph: {}
purpose: []
typography_spectrum: 0.31259
