analytics: {}
color:
  brandColors:
    - '#A0C8B8'
    - '#907038'
    - '#808890'
    - '#D0A040'
    - '#C8B888'
  brandStrength: 0.686936
  lightness: 0.44
  rhythmicContrast: 0.505946
  saturation: 0.987774
cta: {}
layout_spectrum: 1
name: Austin Found
opengraph: {}
purpose: []
typography_spectrum: 0.570945
