typography_spectrum: 0.38001
color:
  brandColors:
    - '#ffffff'
    - '#dd0126'
    - '#00949c'
    - '#240203'
    - '#ff9998'
  brandStrength: 0.1875
  lightness: 0.688063
  saturation: 0.835585
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.51038
analytics:
  google: null
  facebook: null
  twitter: null
name: Austin Found
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: We Do the Work
description: Design Discover Deliver
purpose: []
