analytics: {}
color:
  brandColors:
    - '#ff751a'
    - '#640700'
    - '#eab92e'
    - '#8286b3'
    - '#fdfdfb'
  brandStrength: 0.31081
  lightness: 0.605855
  rhythmicContrast: 0.266891
  saturation: 0.889639
cta: {}
layout_spectrum: 0.889639
name: Austin Found
opengraph: {}
purpose: []
typography_spectrum: 0.31259
