name: Austin Found
favicon: null
layout_spectrum: 1
typography_spectrum: 0.570945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff751a'
    - '#640700'
    - '#eab92e'
    - '#8286b3'
    - '#fdfdfb'
  brandStrength: 0.625
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
