analytics: {}
color:
  brandColors:
    - '#B0C0C0'
    - '#204858'
    - '#708888'
    - '#306078'
    - '#000000'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 0.777027
  saturation: 1
cta: {}
layout_spectrum: 0.889639
name: Austin Found
opengraph: {}
purpose: []
typography_spectrum: 0.31259
