analytics: {}
color:
  brandColors:
    - '#ff751a'
    - '#640700'
    - '#eab92e'
    - '#8286b3'
    - '#fdfdfb'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0.712837
  saturation: 0.889639
cta: {}
layout_spectrum: 0.889639
name: Austin Found
opengraph: {}
purpose: []
typography_spectrum: 0.31259
